stages:
  - lint
  - sast
  - build
  - push
  - deploy

lint_code:
  stage: lint
  tags:
    - docker
  image: golangci/golangci-lint@sha256:72bcd68512b4e27540dd3a778a1b7afd45759d8145cfb3c089f1d7af53e718e9
  needs: []
  rules:
    - changes: 
        - "**/*.go"
        - go.mod
        - go.sum
  script:
    - echo "============= Lint Code ============"
    - golangci-lint run --output.json.path golang-lint-report.json  ./... 
    - echo "============= Lint Done ============"
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - golang-lint-report.json

lint_dockerfile:
  stage: lint
  tags:
    - docker
  image: hadolint/hadolint:57e1618d78fd469a92c1e584e8c9313024656623-alpine-amd64
  needs: []
  rules:
    - changes:
        - Dockerfile
  script:
    - echo "============= Lint Dockerfile ============"
    - hadolint -f json Dockerfile > hadolint-report.json
    - echo "============= Lint success! ================="
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - hadolint-report.json

sast_job:
  stage: sast
  tags: 
    - docker
  needs: []
  rules:
    - when: always
  image: semgrep/semgrep@sha256:892ae188a616ee77e5fb6d151602283cb9ec2ed5d4cf5f45f7eace619d9e685b
  variables:
    SEMGREP_APP_TOKEN: ""
  script:
    - echo "============= SCAN APP ============"
    - semgrep scan --config ci/conf/ci-rules.yml --config ci/conf/go-rules.yml --metrics=off --severity ERROR --json --output semgrep-report.json . 
    - echo "============= SCAN DONE ============"
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - semgrep-report.json

build_job:
  stage: build
  tags:
    - docker
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
    exists:
      - Dockerfile
  - when: never
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug
    entrypoint: [""]
  script:
    - echo "=============== Build image ==============="
    - mkdir -p images
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --no-push --tar-path=images/image.tar
    - echo "=============== Build Done ==============="
  artifacts:
    when: on_success
    expire_in: 1 days
    paths:
      - images/

sca_job:
  stage: build
  needs:
    - build_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
      exists:
        - Dockerfile
      when: always
    - when: never
  tags:
    - docker
  image: 
    name: aquasec/trivy@sha256:bcc376de8d77cfe086a917230e818dc9f8528e3c852f7b1aff648949b6258d1c
    entrypoint: [""]
  script:
    - echo "=============== Run SCA check ==============="
    - trivy image --input images/image.tar --severity=HIGH,CRITICAL -f json -o trivy-report.json --exit-code 1
    - echo "=============== SCA check Done ==============="
  artifacts:
    expire_in: 7 days
    paths:
      - images/ 
      - trivy-report.json
    when: always

push_job:
  stage: push
  needs:
    - sca_job
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v.*/'
      when: always
    - when: never
  variables:
    APP_NAME: currency_api
  image:
    name: quay.io/skopeo/stable@sha256:45ba953b9fd686af45b7f251410c8e923775745aa969f3dba8b467d453d6c7ee
    entrypoint: [""]
  script:
    - echo "=============== Push image to docker hub ==============="
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        IMAGE_TAG="$CI_COMMIT_TAG"$CI_COMMIT_SHA
      else
        IMAGE_TAG="$CI_COMMIT_SHA"
      fi
      skopeo copy --dest-creds "$DOCKER_HUB_USER:$DOCKER_HUB_TOKEN" docker-archive:images/image.tar "docker://docker.io/$DOCKER_HUB_USER/$APP_NAME:$IMAGE_TAG"
    - echo "=============== Image pushed successfully ==============="

trigger:deploy:staging:
  stage: deploy
  variables:
    ENVIRONMENT: "production"
    IMAGE_TAG: "$CI_COMMIT_SHA"
    APP_NAME: "currencyAPI"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  trigger:
    include:
      - local: ci/.gitlab-ci.deploy.yml
    strategy: depend

trigger:deploy:production:
  stage: deploy
  variables:
    ENVIRONMENT: "staging"
    IMAGE_TAG: "$CI_COMMIT_TAG"
    APP_NAME: "currencyAPI"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
      when: manual
    - when: never
  trigger:
    include:
      - local: ci/.gitlab-ci.deploy.yml
    strategy: depend