services:
  currency:
    image: ${DOCKER_HUB_USER:-"artemi00"}/${APP_NAME:-"currencyAPI"}/${IMAGE_TAG:-"latest"}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - AUTHOR=${AUTHOR:-"a.bezpyatko"}
      - VERSION=${VERSION:-"1.1.0"}
    read_only: true
    cap_drop: ["ALL"]
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
            memory: 256m
            cpus: "0.5"
