all:
  children:
    masters:
      hosts:
        master1:
          ansible_host: 10.184.0.26
          ansible_user: master
    workers:
      hosts:
        worker1:
          ansible_host: 10.184.0.154
          ansible_user: worker
        worker2:
          ansible_host: 10.184.0.155
          ansible_user: worker
  vars:
    ansible_ssh_private_key_file: /home/artem@xata436.online/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
