Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  nodes = [
    { name: "master",  ip: "192.168.56.10", cpu: 2, ram: 2048 },
    { name: "worker1", ip: "192.168.56.11", cpu: 1, ram: 2048 },
    { name: "worker2", ip: "192.168.56.12", cpu: 1, ram: 2048 }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |machine|
      machine.vm.hostname = node[:name]
      machine.vm.network "private_network", ip: node[:ip]

      machine.vm.provider "virtualbox" do |vb|
        vb.name   =  node[:name]
        vb.memory =  node[:ram]
        vb.cpus   =  node[:cpu]
      end
    end
  end
end