---
# tasks file for kubelet

- name: Install required utils
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gpg
      - apt-transport-https
      - python3-debian  
    state: present
    update_cache: yes

- name: Add Kubernetes repository 
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: "https://mirror.yandex.ru/mirrors/pkgs.k8s.io/core/stable/v{{ k8s_version }}/deb/"
    suites: "/"
    components: [""]
    signed_by: "https://mirror.yandex.ru/mirrors/pkgs.k8s.io/core/stable/v{{ k8s_version }}/deb/Release.key"
    state: present

- name: Install kubelet
  ansible.builtin.apt:
    name: "kubelet={{ k8s_version }}*"
    state: present
    update_cache: yes

- name: Hold kubelet version
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
