---
# tasks file for kubectl

- name: Install required utils
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gpg
      - apt-transport-https
      - python3-debian
    state: present
    update_cache: yes

- name: Add Kubernetes repository 
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: "https://mirror.yandex.ru/mirrors/pkgs.k8s.io/core/stable/v{{ k8s_version }}/deb/"
    suites: "/"
    components: [""]
    signed_by: "https://mirror.yandex.ru/mirrors/pkgs.k8s.io/core/stable/v{{ k8s_version }}/deb/Release.key"
    state: present

- name: Install kubectl
  ansible.builtin.apt:
    name: "kubectl={{ k8s_version }}*"
    state: present
    update_cache: yes

- name: Hold kubectl version
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold
