---
# tasks file for calico

- name: Check calico namespace
  ansible.builtin.shell: kubectl get ns calico-system
  register: calico_ns
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  failed_when: no

- name: Install Calico CRDs
  ansible.builtin.command: >
    kubectl apply --server-side=true -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/operator-crds.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: calico_ns.rc != 0

- name: Install Tigera operator
  ansible.builtin.command: >
    kubectl apply --server-side=true -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: calico_ns.rc != 0

- name: Download Calico custom resources
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/custom-resources.yaml
    dest: /tmp/calico-custom-resources.yaml
    mode: "0644"
  when: calico_ns.rc != 0

- name: Apply Calico custom resources
  ansible.builtin.command: >
    kubectl apply -f /tmp/calico-custom-resources.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: calico_ns.rc != 0
