stages:
  - deploy
  - smoke

variables:
  APP_NAME: "${APP_NAME}"
  IMAGE_TAG: "${IMAGE_TAG}"
  ENVIRONMENT: "${ENVIRONMENT}"
  DEPLOY_REPO_URL: "https://ci-bot:${DEPLOY_REPO_TOKEN}@education-git.yadro.com/education/devops/2026/a.bezpyatko/app-deployment.git"

deploy_job:
  stage: deploy
  image: alpine/git:2.43.0
  tags:
    - docker
  before_script:
    - |
      git config --global user.email "ci@mail.com"
      git config --global user.name "GitLab CI"
      if [ "$ENVIRONMENT" = "production" ]; then
        VALUES_FILE="environments/prod-values.yaml"
      else
        VALUES_FILE="environments/staging-values.yaml"
      fi
  script:
    - git clone "$DEPLOY_REPO_URL" deploy-repo
    - sed -i "s/^  tag:.*/  tag: ${IMAGE_TAG}/" "deploy-repo/$VALUES_FILE"
    - grep "tag:" "deploy-repo/$VALUES_FILE"
    - cd deploy-repo
    - git add "$VALUES_FILE"
    - git diff --staged --quiet && echo "No changes" && exit 0
    - git commit -m "ci: deploy ${APP_NAME}:${IMAGE_TAG} to ${ENVIRONMENT} [skip ci]"
    - git push origin main

smoke_test:
  stage: smoke
  image: curlimages/curl:8.5.0
  tags:
    - "${ENVIRONMENT}_shell"
  script:
    - |
      if [ "$ENVIRONMENT" = "production" ]; then
        HOST="https://currency.xata436.ru/info"
      else
        HOST="https://dev.xata436.ru/info"
      fi
      sleep 15
      curl -f -v "$HOST" || exit 1