stages:
  - deploy
  - smoke

variables:
  APP_NAME: "${APP_NAME}"
  IMAGE_TAG: "${IMAGE_TAG}"
  ENVIRONMENT: "${ENVIRONMENT}"
  DEPLOY_REPO: "https://ci-bot:${DEPLOY_REPO_TOKEN}@education-git.yadro.com/education/devops/2026/app-deployment.git"

deploy_job:
  stage: deploy
  image: alpine/git:latest
  tags:
    - docker 
  script:
    - echo "========= Deploy to ${ENVIRONMENT} ========="

    - |
      if [ "$ENVIRONMENT" = "production" ]; then
        VALUES_FILE="environments/prod-values.yaml"
      else
        VALUES_FILE="environments/staging-values.yaml"
      fi
    - git clone "$DEPLOY_REPO" deploy-repo
    - cd deploy-repo

    - |
      sed -i "s/^  tag:.*/  tag: ${IMAGE_TAG}/" "$VALUES_FILE"
    - grep "tag:" "$VALUES_FILE"

    - git config user.email "ci@mail.com"
    - git config user.name "GitLab CI"
    - git add "$VALUES_FILE"
    - git commit -m "ci: deploy ${APP_NAME}:${IMAGE_TAG} to ${ENVIRONMENT} [skip ci]"
    - git push origin main

smoke_test:
  stage: smoke
  tags:
    - "${ENVIRONMENT}_shell"
  script:
    - echo "======== Smoke test ========"
    - |
      if [ "$ENVIRONMENT" = "production" ]; then
        HOST="https://currency.xata436.ru/info"
      else
        HOST="https://dev.xata436.ru/info"
      fi
    - sleep 15
    - curl -v "${HOST}" || exit 1